[package]
name = "ratatui-state-examples"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre = "0.6"
crossterm = "0.29"
ratatui = { workspace = true, features = ["unstable-widget-ref"] }
