[package]
name = "release-header"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre.workspace = true
ratatui.workspace = true

[lints]
workspace = true
