[package]
name = "table-detail-tea"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre.workspace = true
crossterm.workspace = true
fakeit = "1.1"
ratatui.workspace = true

[lints]
workspace = true
